client_id: 3MVG9y6x0357HledZQgj1XEr5IuwMGYMtYqq86biDs3sHfWEQ1pTWrEM73Im9mR4sD1iPLiWel_9yOqwP2ncy
client_secret: 8078144587612719927
username: alex@sales4startups.org
password: Fifa4Life9g0vnr1CXoEXWcRgPFYHfzpPH
host: login.salesforce.com
debugging: true