client_id: 3MVG9y6x0357HledZQgj1XEr5IhuOthmeotwXgUu72ENiZmZ59AKZCnQI6GKrsXDMBpYSC5atDb5i0zeU_5Uq
client_secret: 587466380964984175
username: alex@sales4startups.org
password: Fifa4Life9g0vnr1CXoEXWcRgPFYHfzpPH
host: login.salesforce.com
debugging: true