client_id: 3MVG9y6x0357HledZQgj1XEr5IilzYK68ewOkmN9bgVxZtyMlDY8_QqVB_Fg9GqK7.SQjoXD5fsBqF49nDHLR
client_secret: 3725793166232094938
username: alex@sales4startups.org
password: Fifa4Life9g0vnr1CXoEXWcRgPFYHfzpPH
host: login.salesforce.com
debugging: true